language: php
php:
  - '7.2'

before_script:
  - 'composer install'
  - 'curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter'
  - 'chmod +x ./cc-test-reporter'
  - './cc-test-reporter before-build'

after_script:
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'